filters: {}
rules:
  preset-ja-spacing:
    ja-space-between-half-and-full-width:
      space: always
    ja-space-around-code:
      before: true
      after: true
  preset-ja-technical-writing:
    no-exclamation-question-mark: false
    ja-no-mixed-period: false
    max-kanji-continuous-len: false
